- name: Palo Alto Playbook
  hosts: PA45
  gather_facts: false
  connection: local
  
  vars:
    palo_provider:
      ip_address: '192.168.100.45'
      username: 'apidmin'
      password: '2wsx@WSX'
      api_key: 'LUFRPT14c2UyZms2Wk5LQ2R0VDFKamZJUHJLNG9tNE09ZVZMV2wrQ2xwWnVmQVBzOGJGRnBmdlVoZ0d0WXo4c2syYmROZEJMMktMcG9oYUJpWm5nRkNzRzJhWjJ6TURPUw=='

  tasks:
    - name: Issue firewall shutdown command
      paloaltonetworks.panos.panos_op:
        provider: '{{ palo_provider }}'
        cmd: '<request><shutdown><system></system></shutdown></request>'
        cmd_is_xml: true
      register: "cmd_output"
      failed_when: '"Command succeeded with no output" not in cmd_output.msg'
